# Generated by Django 4.2.30 on 2026-05-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_seed_inventory_from_sparepart"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
