# Generated by Django 4.2.30 on 2026-05-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_add_archive_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="qr_code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated from SKU. Used in PART QR format.",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="sparepart",
            index=models.Index(
                fields=["qr_code"], name="inventory_s_qr_code_813df7_idx"
            ),
        ),
    ]
