# Generated by Django 4.2.30 on 2026-05-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_add_supplier_lastcost_status_to_sparepart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="last_purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Most recent unit purchase price.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
