# Generated by Django 4.2.30 on 2026-05-22 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0017_add_allow_operator_consumption_consumableassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0008_alter_sparepart_last_purchase_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="allow_operator_consumption",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, operators can self-log this item via /consumables/",
            ),
        ),
        migrations.CreateModel(
            name="ConsumableAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SELF_SERVICE", "Self Service"),
                            ("SUPERVISOR_ISSUE", "Supervisor Issue"),
                            ("WO_CONSUMPTION", "Work Order Consumption"),
                        ],
                        db_index=True,
                        default="SELF_SERVICE",
                        max_length=32,
                    ),
                ),
                ("approved", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumed_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_consumables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.machine",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumable_assignments",
                        to="inventory.sparepart",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumable_assignments",
                        to="maintenance.site",
                    ),
                ),
                (
                    "stock_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumable Assignment",
                "verbose_name_plural": "Consumable Assignments",
                "ordering": ["-created_at"],
            },
        ),
    ]
