# Generated by Django 4.2.30 on 2026-05-22

from decimal import Decimal

from django.db import migrations


def seed_consumables(apps, schema_editor):
    SparePart = apps.get_model("inventory", "SparePart")
    Inventory = apps.get_model("inventory", "Inventory")
    Site = apps.get_model("maintenance", "Site")

    site = Site.objects.filter(is_default=True).first()
    if not site:
        # No default site — skip inventory seeding
        site = None

    consumables = [
        {
            "sku": "GREASE-5L",
            "name": "Grease 5L",
            "category": "Lubricants",
            "unit": "EA",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("10"),
            "min_stock_level": Decimal("5"),
            "last_purchase_cost": Decimal("45.0000"),
        },
        {
            "sku": "GLOVES-N",
            "name": "Safety Gloves",
            "category": "Safety",
            "unit": "PK",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("50"),
            "min_stock_level": Decimal("20"),
            "last_purchase_cost": Decimal("8.5000"),
        },
        {
            "sku": "CLEANER-01",
            "name": "Industrial Cleaner",
            "category": "Cleaning",
            "unit": "BTL",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("25"),
            "min_stock_level": Decimal("10"),
            "last_purchase_cost": Decimal("12.0000"),
        },
        {
            "sku": "OIL-ENGINE",
            "name": "Engine Oil",
            "category": "Lubricants",
            "unit": "L",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("40"),
            "min_stock_level": Decimal("15"),
            "last_purchase_cost": Decimal("18.5000"),
        },
        {
            "sku": "ZIP-100",
            "name": "Zip Ties",
            "category": "Fasteners",
            "unit": "PK",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("100"),
            "min_stock_level": Decimal("30"),
            "last_purchase_cost": Decimal("3.0000"),
        },
        {
            "sku": "TAPE-ELEC",
            "name": "Electrical Tape",
            "category": "Electrical",
            "unit": "RL",
            "is_consumable": True,
            "allow_operator_consumption": True,
            "status": "active",
            "quantity_on_hand": Decimal("60"),
            "min_stock_level": Decimal("20"),
            "last_purchase_cost": Decimal("5.5000"),
        },
    ]

    for data in consumables:
        part, created = SparePart.objects.update_or_create(
            sku=data["sku"],
            defaults=data,
        )
        # Seed inventory for the default site
        if site:
            Inventory.objects.get_or_create(
                part=part,
                site=site,
                defaults={"quantity_available": data["quantity_on_hand"]},
            )


def reverse_seed(apps, schema_editor):
    SparePart = apps.get_model("inventory", "SparePart")
    SparePart.objects.filter(sku__in=[
        "GLOVES-N", "CLEANER-01", "OIL-ENGINE", "ZIP-100", "TAPE-ELEC"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_add_allow_operator_consumption_consumableassignment"),
    ]

    operations = [
        migrations.RunPython(seed_consumables, reverse_seed),
    ]
