# Generated by Django 4.2.30 on 2026-06-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_existing_lines(apps, schema_editor):
    """Existing PartIssueLine rows were created via the legacy manager
    direct-issue flow. They already deducted stock and created a
    StockMovement. Backfill them as APPROVED, with approved_by =
    issued_by (the manager who issued) and approved_at = created_at.
    """
    PartIssueLine = apps.get_model("inventory", "PartIssueLine")
    for line in PartIssueLine.objects.all():
        if not line.approved_by_id and line.issued_by_id:
            line.approved_by_id = line.issued_by_id
            line.approved_at = line.created_at
        if not line.status:
            line.status = "approved"
        line.save(update_fields=["approved_by", "approved_at", "status"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0010_seed_operator_consumables"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_issues_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="is_emergency_auto_approved",
            field=models.BooleanField(
                default=False,
                help_text="True when the line was auto-approved due to the parent WO being an emergency. Manager should review the cost and edit the qty if needed.",
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Technician who added the request (null when created by manager).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_issues_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="partissueline",
            name="issued_by",
            field=models.ForeignKey(
                help_text="The actor who caused the stock deduction. For manager direct-issue, this is the manager. For technician emergency auto-approve, this is the technician. Set at approval time for non-emergency approvals.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="part_issues_issued",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_existing_lines, noop_reverse),
    ]
