# Generated by Django 4.2.30 on 2026-06-12 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0033_alter_machine_asset_code"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0012_add_part_issue_line_qty_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="manager_note",
            field=models.TextField(
                blank=True,
                help_text="Manager's free-text comment attached to this part line.",
            ),
        ),
        migrations.CreateModel(
            name="PartShortageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending manager review"),
                            ("approved", "Approved (Sprint 4 will auto-create PR)"),
                            ("rejected", "Rejected (reason shown to technician)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("qty_requested", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "qty_issued",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "available_qty_snapshot",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "reserved_qty_snapshot",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "usable_qty_snapshot",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "machine_criticality_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the source machine's criticality at report time.",
                        max_length=20,
                    ),
                ),
                (
                    "part_criticality_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the part's criticality. Empty until part-criticality is added in Sprint 4+.",
                        max_length=20,
                    ),
                ),
                (
                    "wo_priority_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the source WO's priority at report time. Managers approve based on urgency.",
                        max_length=20,
                    ),
                ),
                ("shortage_qty", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "expected_availability_date",
                    models.DateField(
                        blank=True,
                        help_text="Manager's estimate of when the part will be back. Visible to the technician as '📦 Awaiting Procurement'.",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Tech's note when raising the report."
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Manager's reason for rejection. Required when status=REJECTED. Shown to the technician.",
                    ),
                ),
                (
                    "decision_note",
                    models.TextField(
                        blank=True,
                        help_text="Manager's free-text decision note (used for both approve and reject).",
                    ),
                ),
                ("is_emergency", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="part_shortage_reports",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortage_reports",
                        to="inventory.sparepart",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortage_reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shortage_reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when source is a WO. Null for other sources.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortage_reports",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="inventory_p_content_1b2264_idx",
                    ),
                    models.Index(
                        fields=["part", "status"], name="inventory_p_part_id_6c49b9_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="partshortagereport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("content_type", "object_id", "part"),
                name="unique_pending_shortage_per_source_part",
            ),
        ),
    ]
