# Generated by Django 4.2.30 on 2026-06-13 13:46

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0013_partissueline_manager_note_partshortagereport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="related_shortage_report",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this line is the execution record for a shortage report. Set atomically in request_part_on_wo. Used by execute_warehouse_issue to find the report via explicit FK link, not by (wo, part) lookup.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_lines",
                to="inventory.partshortagereport",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity_reserved",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Aggregate reserved quantity, used for planning/reporting purposes. Reservations are soft claims: warehouse issue operations validate against quantity_available only, not against quantity_available minus quantity_reserved. Do NOT add a hard physical-lock check here.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="partshortagereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending manager decision"),
                    (
                        "approved",
                        "Manager decision recorded (editable, no execution yet)",
                    ),
                    (
                        "in_fulfillment",
                        "Execution started (warehouse issue or PR in progress)",
                    ),
                    (
                        "fulfilled",
                        "All committed units issued and/or procured (manager-verified)",
                    ),
                    (
                        "blocked",
                        "Operational problem (PR cancelled, reservation conflict, etc.)",
                    ),
                    ("closed", "Manager-verified closure (terminal)"),
                    ("rejected", "Manager rejected (terminal)"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PartShortageDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("approve", "Approve (issue and/or procure committed)"),
                            ("reject", "Reject (nothing committed, full qty rejected)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "approved_issue_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "approved_procurement_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "rejected_qty",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                ("expected_availability_date", models.DateField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("last_edited_at", models.DateTimeField(auto_now=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("decision_note", models.TextField(blank=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortage_decisions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortage_decisions_edited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="inventory.partshortagereport",
                    ),
                ),
            ],
        ),
    ]
