# Generated by Django 4.2.30 on 2026-06-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_partissueline_related_shortage_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="previous_attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="v4.9 A5: If this line is a re-review request, points to the refused line it replaces. Preserves the audit trail of the original decision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="re_reviews",
                to="inventory.partissueline",
            ),
        ),
    ]
