# Generated by Django 4.2.30 on 2026-06-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0036_alter_notification_kind"),
        ("inventory", "0015_partissueline_previous_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="quantity_quarantine",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Damaged units received from suppliers. Not visible to maintenance. Distinct from quantity_available (usable) and quantity_rejected (audit only).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="quantity_rejected",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Units rejected at inspection. Not in inventory; tracked for audit only.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="allocated_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Stage 3: units reserved in inventory. Set by approve_part_request. PART WO Blocker resolves when issued_qty == approved_qty (not at allocation).",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="partissueline",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("allocated", "Allocated"),
                    ("issued", "Issued"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.CharField(blank=True, max_length=200)),
                (
                    "priority_at_creation",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Snapshot of WO priority rank when the reservation was created",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.sparepart",
                    ),
                ),
                (
                    "source_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="The PartIssueLine that created this reservation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="inventory.partissueline",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nullable for legacy/synthetic reservations",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["part", "status"], name="inventory_i_part_id_e027ac_idx"
                    ),
                    models.Index(
                        fields=["work_order", "status"],
                        name="inventory_i_work_or_b12934_idx",
                    ),
                ],
            },
        ),
    ]
