# Generated by Django 4.2.30 on 2026-07-10 21:12

import os

from django.db import migrations, models
import django.db.models.deletion


def _backfill_supplier_fk(apps, schema_editor):
    """Backfill StockMovement.supplier from supplier_name.

    Tie-breaker (per locked plan):
        1. Exact case match → use it
        2. One case-insensitive match → use it
        3. Multiple case-insensitive matches → leave NULL, log

    Idempotent: only fills rows where supplier_id IS NULL.
    The audit snapshot field `supplier_name` stays — it's the immutable
    record of the supplier name at the time of the stock movement,
    even if the Supplier is later renamed or deleted.
    """
    StockMovement = apps.get_model("inventory", "StockMovement")
    Supplier = apps.get_model("procurement", "Supplier")

    log_lines = []
    filled = 0
    skipped_ambiguous = 0
    skipped_no_match = 0

    qs = StockMovement.objects.filter(
        supplier__isnull=True,
    ).exclude(supplier_name="").only("id", "supplier_name")

    for movement in qs.iterator(chunk_size=500):
        name = (movement.supplier_name or "").strip()
        if not name:
            continue

        # 1. Exact case match
        exact = Supplier.objects.filter(name=name).first()
        if exact is not None:
            movement.supplier = exact
            movement.save(update_fields=["supplier"])
            filled += 1
            continue

        # 2. Case-insensitive match (exactly one)
        ci_qs = Supplier.objects.filter(name__iexact=name)
        ci_count = ci_qs.count()
        if ci_count == 1:
            movement.supplier = ci_qs.first()
            movement.save(update_fields=["supplier"])
            filled += 1
            continue

        # 3. Ambiguous (or zero matches)
        if ci_count > 1:
            ids = sorted(str(pk) for pk in ci_qs.values_list("pk", flat=True))
            log_lines.append(
                f"Skipped ambiguous supplier: movement_id={movement.id} "
                f"supplier_name={name!r} matches={ids}"
            )
            skipped_ambiguous += 1
        else:
            skipped_no_match += 1

    log_path = os.path.join(os.path.dirname(__file__), "0018_backfill_supplier.log")
    with open(log_path, "w", encoding="utf-8") as fh:
        fh.write("# Backfill summary (StockMovement.supplier FK)\n")
        fh.write(f"filled={filled}\n")
        fh.write(f"skipped_no_match={skipped_no_match}\n")
        fh.write(f"skipped_ambiguous={skipped_ambiguous}\n")
        fh.write("\n# Ambiguous rows\n")
        for line in log_lines:
            fh.write(line + "\n")


def _backfill_supplier_fk_reverse(apps, schema_editor):
    """No-op reverse: FK is dropped with the field on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_alter_supplier_code"),
        ("inventory", "0017_drop_inventory_quantity_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier that provided (or received) the part. Nullable for adjustments, consumable self-service, and historical rows. See `supplier_name` for the immutable audit snapshot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="procurement.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="supplier_name",
            field=models.CharField(
                blank=True,
                help_text="Immutable audit snapshot of the supplier name at the time of the movement. Kept even when `supplier` is renamed or deleted.",
                max_length=255,
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["supplier", "movement_type"], name="stockmv_supplier_mvmt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["part", "supplier"], name="stockmv_part_supplier_idx"
            ),
        ),
        migrations.RunPython(_backfill_supplier_fk, _backfill_supplier_fk_reverse),
    ]
