# Generated by Django 4.2.30 on 2026-07-20 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0018_stockmovement_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="emergency_review_note",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="emergency_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("approved", "Approve"),
                    ("exception", "Mark as Exception"),
                    ("investigate", "Investigate Misuse"),
                ],
                help_text="Manager post-review on an emergency auto-issued line. Empty until reviewed. None of the three outcomes reverts the inventory or the cost — stock stays consumed, cost stays posted.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="emergency_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="emergency_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="part_issues_emergency_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
