# Generated by Django 4.2.30 on 2026-07-20 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_phase3_emergency_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="partissueline",
            name="activity_label",
            field=models.CharField(
                blank=True,
                help_text="Display label for the activity (free text, optional). Used for human readability in lists and the WO detail timeline.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="partissueline",
            name="activity_uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Stable identity for this line's maintenance activity. Not part of any uniqueness constraint — duplicate prevention is handled at the service layer. Used for grouping lines of the same activity, audit cross-references, and Phase 2.5+ Activity model extraction.",
            ),
        ),
    ]
