# Generated by Django 4.2.30 on 2026-07-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0020_phase5_activity_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("spare_part", "Spare Part"),
                    ("consumable", "Consumable"),
                    ("reusable_tool", "Reusable Tool"),
                ],
                db_index=True,
                default="spare_part",
                help_text="spare_part = normal inventory item; consumable = decreases when issued; reusable_tool = managed as physical units in a tool pool.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReusableToolInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_number",
                    models.PositiveIntegerField(
                        help_text="Human-readable sequence number, unique per part. Displayed as '{part.name} #{tool_number}'."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("out_of_service", "Out of Service"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive instances are hidden from default listings but history is preserved. Use this for written-off tools instead of deleting the row.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "part",
                    models.ForeignKey(
                        limit_choices_to={"item_type": "reusable_tool"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_instances",
                        to="inventory.sparepart",
                    ),
                ),
                (
                    "source_stock_movement",
                    models.ForeignKey(
                        blank=True,
                        help_text="The 'Issue to Tool Pool' StockMovement that created this unit. Source of truth for cost/date/supplier/PO via JOIN. May be null for legacy or manually-created instances.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_instances",
                        to="inventory.stockmovement",
                    ),
                ),
            ],
            options={
                "ordering": ["part_id", "tool_number"],
                "indexes": [
                    models.Index(
                        fields=["part", "status"], name="inventory_r_part_id_631fba_idx"
                    ),
                    models.Index(
                        fields=["status", "is_active"],
                        name="inventory_r_status_850b84_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reusabletoolinstance",
            constraint=models.UniqueConstraint(
                fields=("part", "tool_number"), name="unique_tool_number_per_part"
            ),
        ),
    ]
