# Generated by Django 4.2.30 on 2026-07-22 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0055_remove_tool_supplier_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0021_sparepart_item_type_reusabletoolinstance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_at", models.DateTimeField()),
                (
                    "return_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "condition_out",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=10,
                    ),
                ),
                (
                    "condition_in",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("damaged", "Damaged"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="inventory.reusabletoolinstance",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_assignments",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checkout_at"],
            },
        ),
        migrations.CreateModel(
            name="ToolDamageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("damage_date", models.DateTimeField()),
                ("reason", models.TextField()),
                (
                    "repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Set when the manager marks the report as repaired.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("repaired", "Repaired"),
                            ("written_off", "Written Off"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The return that triggered this report, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_reports",
                        to="inventory.toolassignment",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="damage_reports",
                        to="inventory.reusabletoolinstance",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_damage_reports",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_damage_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_damage_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-damage_date"],
            },
        ),
        migrations.CreateModel(
            name="ToolMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("issued", "Issued to Tool Pool"),
                            ("assigned", "Assigned"),
                            ("returned", "Returned"),
                            ("damaged", "Damaged"),
                            ("repaired", "Repaired"),
                            ("written_off", "Written Off"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.toolassignment",
                    ),
                ),
                (
                    "damage_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.tooldamagereport",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.reusabletoolinstance",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tool_movements",
                        to="maintenance.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["instance", "-created_at"],
                        name="inventory_t_instanc_8ddb59_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="inventory_t_actor_i_1643a0_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "-created_at"],
                        name="inventory_t_movemen_a4101b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="tooldamagereport",
            index=models.Index(
                fields=["instance", "status"], name="inventory_t_instanc_b6fed3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tooldamagereport",
            index=models.Index(
                fields=["status", "damage_date"], name="inventory_t_status_264076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolassignment",
            index=models.Index(
                fields=["operator", "return_at"], name="inventory_t_operato_8e69cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolassignment",
            index=models.Index(
                fields=["machine", "return_at"], name="inventory_t_machine_3aa2c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="toolassignment",
            index=models.Index(
                fields=["instance", "return_at"], name="inventory_t_instanc_8169d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="toolassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("return_at__isnull", True)),
                fields=("instance",),
                name="one_open_assignment_per_instance",
            ),
        ),
    ]
