# Generated by Django 4.2.30 on 2026-07-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_toolassignment_tooldamagereport_toolmovement_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventoryreservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("source_line",),
                name="uniq_active_reservation_per_line",
            ),
        ),
        migrations.AddConstraint(
            model_name="partissueline",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "approved", "allocated"])
                ),
                fields=("work_order", "part"),
                name="unique_active_pil_per_wo_part",
            ),
        ),
    ]
