# Generated by Django 4.2.30 on 2026-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0023_inventoryreservation_uniq_active_reservation_per_line_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["part", "-created_at"], name="stockmv_part_created_idx"
            ),
        ),
    ]
