from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("scan/", views.qr_scan, name="qr_scan"),
    path("scan/decode/", views.qr_scan_decode, name="qr_scan_decode"),
    path("machines/", views.machine_list, name="machine_list"),
    path("machines/new/", views.machine_create, name="machine_create"),
    path("machines/<int:pk>/edit/", views.machine_edit, name="machine_edit"),
    path("issues/", views.issue_list, name="issue_list"),
    path("issues/new/", views.issue_create, name="issue_create"),
    path("issues/<int:pk>/validate/", views.issue_validate, name="issue_validate"),
    path("work-orders/", views.work_order_list, name="work_order_list"),
    path("work-orders/emergency/", views.emergency_work_order_create, name="emergency_wo_create"),
    path("work-orders/<int:pk>/", views.work_order_detail, name="work_order_detail"),
    path("work-orders/from-issue/<int:issue_pk>/", views.work_order_create_from_issue, name="work_order_create"),
    path("work-orders/<int:pk>/assign/", views.work_order_assign, name="work_order_assign"),
    path("work-orders/<int:pk>/start/", views.work_order_start, name="work_order_start"),
    path("work-orders/<int:pk>/pause/", views.work_order_pause, name="work_order_pause"),
    path("work-orders/<int:pk>/mark-parts/", views.work_order_mark_parts, name="work_order_mark_parts"),
    path("work-orders/<int:pk>/mark-vendor/", views.work_order_mark_vendor, name="work_order_mark_vendor"),
    path("work-orders/<int:pk>/submit/", views.work_order_submit, name="work_order_submit"),
    path("work-orders/<int:pk>/close/", views.work_order_close, name="work_order_close"),
    path("work-orders/<int:pk>/issue-part/", views.work_order_issue_part, name="work_order_issue_part"),
    path("stock/", views.stock_dashboard, name="stock_dashboard"),
    path("stock/in/", views.stock_in_view, name="stock_in"),
    path("consumables/", views.consumables_view, name="consumables"),
    path("pm/", views.pm_list, name="pm_list"),
    path("pm/new/", views.pm_create, name="pm_create"),
    path("pm/<int:pk>/spawn-wo/", views.pm_spawn_wo, name="pm_spawn_wo"),
    path("tools/", views.tool_list, name="tool_list"),
    path("tools/new/", views.tool_create, name="tool_create"),
    path("tools/<int:pk>/edit/", views.tool_edit, name="tool_edit"),
    path("tools/assign/", views.tool_assign, name="tool_assign"),
    path("tools/return/<int:assignment_pk>/", views.tool_return, name="tool_return"),
    path("repairs/", views.repair_list, name="repair_list"),
    path("repairs/new/", views.repair_create, name="repair_create"),
    path("repairs/<int:pk>/officer/", views.repair_officer, name="repair_officer"),
    path("quick-log/", views.quick_log, name="quick_log"),
    path("reports/", views.reports_view, name="reports"),
    path("notifications/", views.notification_list, name="notification_list"),
    path("notifications/<int:pk>/read/", views.notification_mark_read, name="notification_mark_read"),
    path("notifications/read-all/", views.notification_mark_all_read, name="notification_mark_all_read"),
    path("audit-log/", views.audit_log_list, name="audit_log_list"),
    path("kpis/", views.kpi_dashboard, name="kpi_dashboard"),
    path("repairs/<int:pk>/accept/", views.repair_manager_accept, name="repair_manager_accept"),
]
