# Generated by Django 4.2.30 on 2026-05-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_notification_kind_emergency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("address", models.TextField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "downtime_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="asset_level",
            field=models.PositiveIntegerField(
                choices=[(1, "Plant"), (2, "Line"), (3, "Machine"), (4, "Component")],
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="asset_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("production", "Production"),
                    ("utility", "Utility"),
                    ("safety", "Safety"),
                    ("hvac", "HVAC"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="machines",
                to="maintenance.site",
            ),
        ),
    ]
