# Generated by Django 4.2.30 on 2026-05-20 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0005_seed_default_site"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("work_order", "Work Order"),
                            ("machine", "Machine"),
                            ("spare_part", "Spare Part"),
                            ("purchase_request", "Purchase Request"),
                            ("repair_order", "Repair Order"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=maintenance.models.attachment_upload_path,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=128)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="maintenance_entity__4ad143_idx",
                    )
                ],
            },
        ),
    ]
