# Generated by Django 4.2.30 on 2026-05-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0006_add_attachment_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Downtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "downtime_type",
                    models.CharField(
                        choices=[
                            ("breakdown", "Breakdown"),
                            ("emergency", "Emergency"),
                            ("scheduled", "Scheduled"),
                            ("idle", "Idle"),
                        ],
                        default="breakdown",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=500)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime_records",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "downtime_records",
                "ordering": ["-start_time"],
            },
        ),
    ]
