# Generated by Django 4.2.30 on 2026-05-20 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0009_add_assignment_history_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Failure Category",
                "verbose_name_plural": "Failure Categories",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="machine",
            name="failure_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="machines",
                to="maintenance.failurecategory",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="issue_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Classified failure category (Phase 2: FailureMode sub-classification)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="maintenance.failurecategory",
                verbose_name="Issue Type",
            ),
        ),
        migrations.AddIndex(
            model_name="maintenanceissue",
            index=models.Index(
                fields=["issue_type"], name="maintenance_issue_t_a6c7c0_idx"
            ),
        ),
    ]