# Generated by Django 4.2.30 on 2026-05-21 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0010_add_issue_type_to_maintenance_issue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorderassignmenthistory",
            options={
                "ordering": ["assigned_at"],
                "verbose_name_plural": "work order assignment histories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="workorderassignmenthistory",
            unique_together={("work_order", "technician", "assigned_at")},
        ),
    ]
