# Generated by Django 4.2.30 on 2026-05-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0011_add_unique_together_assignment_history"),
    ]

    operations = []