# Generated by Django 4.2.30 on 2026-05-22 18:58

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0016_notification_is_critical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated 300px thumbnail",
                upload_to=maintenance.models.attachment_thumbnail_path,
            ),
        ),
    ]
