# Generated by Django 4.2.30 on 2026-06-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0020_allow_null_machine_tool_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="pause_note",
            field=models.TextField(
                blank=True,
                help_text="Free-text note for pause. Required when pause_reason='other'.",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="pause_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emergency", "Emergency override (auto-paused)"),
                    ("operational", "Operational interruption"),
                    ("awaiting_parts", "Awaiting parts (short wait)"),
                    ("awaiting_vendor", "Awaiting vendor (short wait)"),
                    ("other", "Other (note required)"),
                ],
                help_text="Why the work order was paused (set on every IN_PROGRESS→PAUSED transition).",
                max_length=20,
            ),
        ),
    ]
