# Generated by Django 4.2.30 on 2026-06-01 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0021_add_pause_reason_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalRepairRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis_note",
                    models.TextField(
                        help_text="Technician's diagnosis: what's wrong with the part"
                    ),
                ),
                (
                    "part_description",
                    models.TextField(
                        help_text="Description of the part being sent out (name, part#, qty)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending manager review"),
                            ("approved", "Approved (ERO created)"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "manager_note",
                    models.TextField(
                        blank=True, help_text="Manager's reason on approve/reject"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repair_order",
                    models.OneToOneField(
                        blank=True,
                        help_text="Set when manager approves — links to the created ERO",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="origin_request",
                        to="maintenance.externalrepairorder",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="external_repair_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_repair_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_repair_requests",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
