# Generated by Django 4.2.30 on 2026-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0022_externalrepairrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue_new", "New issue"),
                    ("issue_validated", "Issue validated"),
                    ("wo_review", "Work order pending review"),
                    ("wo_assigned", "Work order assigned"),
                    ("wo_emergency", "Emergency work order"),
                    ("low_stock", "Low stock"),
                    ("procurement", "Procurement"),
                    ("pm_overdue", "PM overdue"),
                    ("repair_returned", "Repair returned from vendor"),
                    ("repair_requested", "External repair requested"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
