# Generated by Django 4.2.30 on 2026-06-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0023_alter_notification_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrepairorder",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="repair_orders_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="invoice_ref",
            field=models.CharField(
                blank=True,
                help_text="Vendor invoice number. Required on UC-20 acceptance.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="externalrepairorder",
            name="actual_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Final vendor invoice amount. Set by manager on UC-20 acceptance. Required when status moves to CLOSED.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
