# Generated by Django 4.2.30 on 2026-06-02 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0024_externalrepairorder_closed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceissue",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="escalated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="P3.3: user who escalated this issue to emergency status.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenanceissue",
            name="is_emergency",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="P3.3: operator can flag an issue as emergency on creation, or a supervisor/manager can escalate during validation. When True, priority auto-sets to CRITICAL and any WO created from this issue inherits is_emergency=True.",
            ),
        ),
    ]
