# Generated by Django 4.2.30 on 2026-06-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0025_maintenanceissue_escalated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue_new", "New issue"),
                    ("issue_validated", "Issue validated"),
                    ("issue_stale", "Stale issue (not validated)"),
                    ("wo_created", "Work order created from issue"),
                    ("wo_review", "Work order pending review"),
                    ("wo_assigned", "Work order assigned"),
                    ("wo_started", "Work order started"),
                    ("wo_paused", "Work order paused / waiting"),
                    ("wo_closed", "Work order closed"),
                    ("wo_emergency", "Emergency work order"),
                    ("low_stock", "Low stock"),
                    ("procurement", "Procurement"),
                    ("pm_overdue", "PM overdue"),
                    ("repair_returned", "Repair returned from vendor"),
                    ("repair_requested", "External repair requested"),
                    ("repair_draft", "External repair order created (needs vendor)"),
                    ("repair_sent", "External repair sent to vendor"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="pause_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emergency", "Emergency override (auto-paused)"),
                    ("operational", "Operational interruption"),
                    ("other", "Other (note required)"),
                ],
                help_text="Why the work order was paused (set on every IN_PROGRESS→PAUSED transition).",
                max_length=20,
            ),
        ),
    ]
