# Generated by Django 4.2.30 on 2026-06-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0026_alter_notification_kind_alter_workorder_pause_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("LABEL", "Label"),
                    ("PACKAGING", "Packaging"),
                    ("INSTALLED", "Installed"),
                    ("DOCUMENT", "Document"),
                ],
                default="PRODUCT",
                help_text="Category of attachment image",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Primary/default image for this entity"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="asset_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hierarchical asset code (e.g. FM-01-CONV-BRG-001)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="criticality",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                help_text="Criticality rating (level-5 Component)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="expected_life_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Expected service life in days (level-5 Component)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="install_date",
            field=models.DateField(
                blank=True, help_text="Date installed (level-5 Component)", null=True
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="manufacturer",
            field=models.CharField(
                blank=True, help_text="Manufacturer (level-5 Component)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="model_number",
            field=models.CharField(
                blank=True, help_text="Model number (level-5 Component)", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Serial number (level-5 Component)",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("retired", "Retired"),
                    ("awaiting_repair", "Awaiting Repair"),
                ],
                default="active",
                help_text="Component status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="asset_level",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Area"),
                    (2, "Production Line"),
                    (3, "Machine"),
                    (4, "Subassembly"),
                    (5, "Component"),
                ],
                default=3,
            ),
        ),
    ]
