# Generated by Django 4.2.30 on 2026-06-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0027_attachment_category_attachment_is_primary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmschedule",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Level-5 Component this PM targets (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_component_schedules",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="Level-5 Component this WO targets (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="component_work_orders",
                to="maintenance.machine",
            ),
        ),
    ]
