# Generated by Django 4.2.30 on 2026-06-08 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0028_pmschedule_component_workorder_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceissue",
            name="component",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"asset_level": 5},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="component_issues",
                to="maintenance.machine",
            ),
        ),
    ]
