# Generated by Django 4.2.30 on 2026-06-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0029_maintenanceissue_component"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrepairorder",
            name="component",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"asset_level": 5},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="component_external_repair_orders",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_repair_orders",
                to="maintenance.machine",
            ),
        ),
    ]
