# Generated by Django 4.2.30 on 2026-06-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0032_attachment_pm_schedule_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="asset_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hierarchical asset code (e.g. FM-01-CONV-BRG-001)",
                max_length=128,
            ),
        ),
    ]
