# Generated by Django 4.2.30 on 2026-06-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0035_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue_new", "New issue"),
                    ("issue_validated", "Issue validated"),
                    ("issue_stale", "Stale issue (not validated)"),
                    ("wo_created", "Work order created from issue"),
                    ("wo_review", "Work order pending review"),
                    ("wo_assigned", "Work order assigned"),
                    ("wo_started", "Work order started"),
                    ("wo_paused", "Work order paused / waiting"),
                    ("wo_closed", "Work order closed"),
                    ("wo_emergency", "Emergency work order"),
                    ("low_stock", "Low stock"),
                    ("part_shortage", "Part shortage reported"),
                    ("procurement", "Procurement"),
                    ("pm_overdue", "PM overdue"),
                    ("repair_returned", "Repair returned from vendor"),
                    ("repair_requested", "External repair requested"),
                    ("repair_draft", "External repair order created (needs vendor)"),
                    ("repair_sent", "External repair sent to vendor"),
                    ("part_received", "Part received against PO"),
                    ("vendor_return", "Vendor returned spare part"),
                    ("shortage_followup", "Shortage follow-up"),
                    ("wo_part_received", "Part received from supplier (linked to WO)"),
                    ("wo_part_returned", "Part returned from vendor (linked to WO)"),
                    ("wo_part_rejected", "Part request rejected (linked to WO)"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
