# Generated by Django 4.2.30 on 2026-06-15 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_lifecycle_status(apps, schema_editor):
    """Map legacy WorkOrder.status values to the new lifecycle_status field.

    Legacy status values: approved, assigned, in_progress, paused, waiting_vendor,
    pending_parts, pending_review, closed.
    New lifecycle values:  draft, assigned, in_progress, pending_review, closed, cancelled.
    """
    WorkOrder = apps.get_model("maintenance", "WorkOrder")
    STATUS_MAP = {
        "approved":       "assigned",
        "assigned":       "assigned",
        "in_progress":    "in_progress",
        "paused":         "in_progress",
        "pending_parts":  "in_progress",
        "waiting_vendor": "in_progress",
        "pending_review": "pending_review",
        "closed":         "closed",
    }
    for wo in WorkOrder.objects.all():
        legacy = wo.status
        wo.lifecycle_status = STATUS_MAP.get(legacy, "assigned")
        wo.save(update_fields=["lifecycle_status"])


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0016_inventory_quantity_quarantine_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("maintenance", "0036_alter_notification_kind"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workordercost",
            old_name="parts_cost",
            new_name="material_cost",
        ),
        migrations.RenameField(
            model_name="workordercost",
            old_name="vendor_cost",
            new_name="vendor_repair_cost",
        ),
        migrations.AddField(
            model_name="attachment",
            name="compressed_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the compressed video file (mp4) — populated by VideoCompressionService",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="is_video",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="attachment",
            name="thumbnail_path",
            field=models.CharField(
                blank=True,
                help_text="Path to a 1-second thumbnail of the video",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="externalrepairrequest",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="The level-3 machine whose part is being sent for repair",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_repair_requests",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="externalrepairrequest",
            name="component",
            field=models.ForeignKey(
                blank=True,
                help_text="The level-5 component where the part is located",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="component_external_repair_requests",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="externalrepairrequest",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_repair_requests",
                to="inventory.sparepart",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="dedup_key",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="blocker_system_version",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="0=created before blocker system; 1+=created under the new system.",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wos_cancelled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In progress"),
                    ("pending_review", "Pending review"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="assigned",
                help_text="Explicit, user-driven state. Replaces the legacy 'status' field for new code.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=backfill_lifecycle_status,
            reverse_code=reverse_backfill,
        ),
        migrations.AddField(
            model_name="workorder",
            name="operational_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("pending_parts", "Pending parts"),
                    ("waiting_vendor", "Waiting vendor"),
                    ("paused", "Paused"),
                ],
                db_index=True,
                default="paused",
                help_text="Derived from open blockers + labor state. Always computed; do not write directly.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workordercost",
            name="downtime_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Phase 2: set by finance team. Computed as Downtime.total_minutes × rate_per_hour.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="workordercost",
            name="procurement_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of POItem.actual_unit_price × received_qty for POs linked via PR to this WO.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="workordercost",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of StockMovement.unit_cost × qty for ISSUE_TO_WO movements on this WO. Renamed from parts_cost.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="workordercost",
            name="vendor_repair_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Sum of ERO.actual_cost for EROs linked via PR/ExternalRepairRequest to this WO. Renamed from vendor_cost.",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="workordercost",
            name="additional_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="workordercost",
            name="consumables_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name="WorkOrderBlocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("part", "Awaiting Spare Part"),
                            ("shortage", "Awaiting Procurement"),
                            ("vendor_repair", "Awaiting Vendor Repair"),
                            ("operational", "Operational Pause"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "external_label",
                    models.CharField(
                        blank=True,
                        help_text="Cached human-readable summary, e.g. 'BRG-6006 × 2' or 'Servo S7-300'",
                        max_length=300,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "pause_reason",
                    models.CharField(
                        blank=True,
                        help_text="'operational' | 'other' | 'emergency' (system-set)",
                        max_length=20,
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True)),
                ("migrated_from_legacy", models.BooleanField(default=False)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blockers_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_ero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers",
                        to="maintenance.externalrepairorder",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blockers_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interruptions_caused",
                        to="maintenance.workorder",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blockers",
                        to="maintenance.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="work_order_blocker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="maintenance.workorderblocker",
            ),
        ),
        migrations.CreateModel(
            name="WorkOrderBlockerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("blocker_created", "Blocker Created"),
                            ("blocker_resolved", "Blocker Resolved"),
                            ("blocker_cancelled", "Blocker Cancelled"),
                            ("part_request_created", "Part Request Created"),
                            ("part_approved", "Part Approved"),
                            ("part_rejected", "Part Rejected"),
                            ("part_issued", "Part Issued"),
                            ("part_received", "Part Received"),
                            ("shortage_raised", "Shortage Raised"),
                            ("shortage_decided", "Shortage Decided"),
                            ("shortage_fulfilled", "Shortage Fulfilled"),
                            ("ero_created", "Ero Created"),
                            ("ero_sent", "Ero Sent"),
                            ("ero_returned", "Ero Returned"),
                            ("ero_accepted", "Ero Accepted"),
                            ("emergency_interrupted", "Emergency Interrupted"),
                            ("labor_resumed", "Labor Resumed"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocker_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="maintenance.workorderblocker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["blocker", "created_at"],
                        name="maintenance_blocker_b031b0_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="maintenance_event_t_3c2eaa_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workorderblocker",
            index=models.Index(
                fields=["work_order", "status"], name="maintenance_work_or_9c4c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorderblocker",
            index=models.Index(
                fields=["status", "kind"], name="maintenance_status_a7e01e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderblocker",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("work_order", "content_type", "object_id"),
                name="uniq_open_blocker_per_wo_ref",
            ),
        ),
    ]
