# Generated by Django 4.2.30 on 2026-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0037_remove_workordercost_parts_cost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorder",
            name="blocker_system_version",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="pause_note",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="pause_reason",
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="status",
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue_new", "New issue"),
                    ("issue_validated", "Issue validated"),
                    ("issue_stale", "Stale issue (not validated)"),
                    ("wo_created", "Work order created from issue"),
                    ("wo_review", "Work order pending review"),
                    ("wo_assigned", "Work order assigned"),
                    ("wo_started", "Work order started"),
                    ("wo_paused", "Work order paused / waiting"),
                    ("wo_closed", "Work order closed"),
                    ("wo_emergency", "Emergency work order"),
                    ("low_stock", "Low stock"),
                    ("part_shortage", "Part shortage reported"),
                    ("procurement", "Procurement"),
                    ("pm_overdue", "PM overdue"),
                    ("repair_returned", "Repair returned from vendor"),
                    ("repair_requested", "External repair requested"),
                    ("repair_draft", "External repair order created (needs vendor)"),
                    ("repair_sent", "External repair sent to vendor"),
                    ("part_received", "Part received against PO"),
                    ("vendor_return", "Vendor returned spare part"),
                    ("shortage_followup", "Shortage follow-up"),
                    ("wo_part_received", "Part received from supplier (linked to WO)"),
                    ("wo_part_returned", "Part returned from vendor (linked to WO)"),
                    ("wo_part_rejected", "Part request rejected (linked to WO)"),
                    ("wo_blocker_opened", "WO blocker opened"),
                    ("wo_blocker_resolved", "WO blocker resolved"),
                    ("wo_blocker_cancelled", "WO blocker cancelled"),
                    ("emergency_interrupted", "Emergency WO interrupted another WO"),
                    ("labor_resumed", "Labor resumed on WO"),
                    ("po_received_summary", "PO received (summary)"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In progress"),
                    ("pending_review", "Pending review"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="assigned",
                help_text="Explicit, user-driven state.",
                max_length=20,
            ),
        ),
    ]
