# Generated by Django 4.2.30 on 2026-06-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0038_remove_workorder_blocker_system_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Signed: positive adds, negative reduces.",
                        max_digits=12,
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        help_text="Required. Min 10 chars. Explains why this adjustment exists.",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_adjustments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_adjustments",
                        to="maintenance.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workordercost",
            name="last_reconciled_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workordercost",
            name="ledger_transaction_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cached count of CostTransaction rows for this WO. Updated by WorkOrderCost.recalculate_from_ledger().",
            ),
        ),
        migrations.CreateModel(
            name="CostTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("vendor_repair", "Vendor Repair"),
                            ("consumable", "Consumable"),
                            ("adjustment", "Adjustment"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        db_index=True,
                        default="SAR",
                        help_text="ISO 4217 currency code. SAR default for this deployment.",
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("part_issue_line", "Part Issue Line"),
                            ("external_repair_order", "External Repair Order"),
                            ("stock_movement", "Stock Movement"),
                            ("cost_adjustment", "Cost Adjustment"),
                            ("calibration", "Calibration"),
                            ("fuel", "Fuel"),
                            ("tool_issue", "Tool Issue"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_reversal",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if this transaction reverses a previous one. Net amount for (source_type, source_id) = SUM(amount) over ALL rows including reversals.",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posted_cost_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "adjustment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="maintenance.costadjustment",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        limit_choices_to={"asset_level": 5},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        limit_choices_to={"asset_level__lte": 4},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="If is_reversal=True, points to the row being reversed. Audit trail.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="maintenance.costtransaction",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_transactions",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["work_order", "category"],
                        name="maintenance_work_or_6bb34b_idx",
                    ),
                    models.Index(
                        fields=["machine", "-occurred_at"],
                        name="maintenance_machine_3f965d_idx",
                    ),
                    models.Index(
                        fields=["component", "-occurred_at"],
                        name="maintenance_compone_a9d58f_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="maintenance_source__85b116_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="costtransaction",
            constraint=models.CheckConstraint(
                check=models.Q(("amount", 0), _negated=True),
                name="cost_transaction_amount_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="costadjustment",
            constraint=models.CheckConstraint(
                check=models.Q(("amount", 0), _negated=True),
                name="cost_adjustment_amount_not_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="costadjustment",
            constraint=models.CheckConstraint(
                check=models.Q(("memo__regex", ".{10,}")),
                name="cost_adjustment_memo_min_10_chars",
            ),
        ),
    ]
