# Generated by Django 4.2.30 on 2026-06-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "maintenance",
            "0039_costadjustment_workordercost_last_reconciled_at_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workordercost",
            name="additional_cost_note",
        ),
        migrations.RemoveField(
            model_name="workordercost",
            name="downtime_cost",
        ),
        migrations.RemoveField(
            model_name="workordercost",
            name="procurement_cost",
        ),
    ]
