# Generated by Django 4.2.30 on 2026-06-22 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0040_phase5_drop_legacy_cost_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workordercost",
            name="committed_material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Sum of (PartIssueLine.approved_qty × unit_cost) for approved / allocated / issued lines. Set at approval time. Distinct from material_cost (which is the actual cost posted to the ledger at warehouse-issue time). Allows the dashboard to show committed vs actual side-by-side. Excludes pending/rejected lines. Falls back to SparePart.last_purchase_cost or avg_cost if line.unit_cost is 0.",
                max_digits=14,
            ),
        ),
    ]
