# Generated by Django 4.2.30 on 2026-06-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0041_add_committed_material_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="blocker_system_version",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="0 = created under legacy single-status model. 1 = created under the new lifecycle/operational/blocker model. Auto-bumped to 1 on the first domain event (part request, pause, etc.) that creates a WorkOrderBlocker row.",
            ),
        ),
    ]
