# Generated by Django 4.2.30 on 2026-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0047_template_photos_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_generate_run", models.DateTimeField(blank=True, null=True)),
                ("morning_summary_sent_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Maintenance settings",
            },
        ),
        migrations.AddField(
            model_name="pmschedule",
            name="due_time",
            field=models.TimeField(
                default="08:00",
                help_text="Time-of-day for scheduled occurrences (used for grouping Today's Schedule)",
            ),
        ),
        migrations.AddField(
            model_name="pmschedule",
            name="ends_at",
            field=models.DateField(
                blank=True,
                help_text="Schedule stops generating occurrences after this date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pmtemplate",
            name="requires_photo_min_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Minimum number of photos the technician must attach when completing this PM",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="photo_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Denormalized count of attached photos — used for fast Complete gating",
            ),
        ),
    ]
