# Generated by Django 4.2.30 on 2026-06-29 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0048_maintenancesettings_pmschedule_due_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pmexecution",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="assigned_technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_executions_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="last_reassignment_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="reassignment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pm_executions_rejected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pmexecution",
            name="rejection_reason",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
