# Generated by Django 4.2.30 on 2026-07-10 21:22

import os

from django.db import migrations, models
import django.db.models.deletion


def _backfill_ero_supplier(apps, schema_editor):
    """Backfill ExternalRepairOrder.supplier from vendor_name.

    Same tie-breaker as StockMovement.supplier (Commit 1):
        1. Exact case match → use it
        2. One case-insensitive match → use it
        3. Multiple case-insensitive matches → leave NULL, log

    Idempotent: only fills rows where supplier_id IS NULL.
    """
    ExternalRepairOrder = apps.get_model("maintenance", "externalrepairorder")
    Supplier = apps.get_model("procurement", "Supplier")

    log_lines = []
    filled = 0
    skipped_ambiguous = 0
    skipped_no_match = 0

    qs = ExternalRepairOrder.objects.filter(supplier__isnull=True).exclude(vendor_name="").only("id", "vendor_name")

    for ero in qs.iterator(chunk_size=500):
        name = (ero.vendor_name or "").strip()
        if not name:
            continue

        # 1. Exact case match
        exact = Supplier.objects.filter(name=name).first()
        if exact is not None:
            ero.supplier = exact
            ero.save(update_fields=["supplier"])
            filled += 1
            continue

        # 2. Case-insensitive (exactly one)
        ci_qs = Supplier.objects.filter(name__iexact=name)
        ci_count = ci_qs.count()
        if ci_count == 1:
            ero.supplier = ci_qs.first()
            ero.save(update_fields=["supplier"])
            filled += 1
            continue

        # 3. Ambiguous or zero matches
        if ci_count > 1:
            ids = sorted(str(pk) for pk in ci_qs.values_list("pk", flat=True))
            log_lines.append(
                f"Skipped ambiguous vendor: ero_id={ero.id} "
                f"vendor_name={name!r} matches={ids}"
            )
            skipped_ambiguous += 1
        else:
            skipped_no_match += 1

    log_path = os.path.join(os.path.dirname(__file__), "0050_backfill_ero_supplier.log")
    with open(log_path, "w", encoding="utf-8") as fh:
        fh.write("# Backfill summary (ExternalRepairOrder.supplier FK)\n")
        fh.write(f"filled={filled}\n")
        fh.write(f"skipped_no_match={skipped_no_match}\n")
        fh.write(f"skipped_ambiguous={skipped_ambiguous}\n")
        fh.write("\n# Ambiguous rows\n")
        for line in log_lines:
            fh.write(line + "\n")


def _backfill_ero_supplier_reverse(apps, schema_editor):
    """No-op reverse: FK is dropped with the field on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_alter_supplier_code"),
        ("maintenance", "0049_pm_execution_owner_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalrepairorder",
            name="diagnosed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp the vendor reported a diagnosis back (after sending, before actual repair). Drives the ERO repair timeline.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="invoice_attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Uploaded scan/photo of the vendor invoice PDF/image. Mirrors PurchaseOrder.invoice_attachment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ero_invoice_for",
                to="maintenance.attachment",
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="invoice_date",
            field=models.DateField(
                blank=True,
                help_text="Date on the vendor invoice. Mirrors PurchaseOrder.supplier_invoice_date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="returned_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp the part physically came back from the vendor. Drives the ERO repair timeline; status is RETURNED at this point.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalrepairorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Supplier (vendor) handling the repair. Nullable for legacy EROs created before this field was added — see `vendor_name` for the immutable snapshot. New EROs should always set this FK.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_repair_orders",
                to="procurement.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="externalrepairorder",
            name="vendor_name",
            field=models.CharField(
                blank=True,
                help_text="Immutable audit snapshot of the vendor name at the time the ERO was sent. Kept even when `supplier` is renamed or deleted.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("issue_new", "New issue"),
                    ("issue_validated", "Issue validated"),
                    ("issue_stale", "Stale issue (not validated)"),
                    ("wo_created", "Work order created from issue"),
                    ("wo_review", "Work order pending review"),
                    ("wo_assigned", "Work order assigned"),
                    ("wo_started", "Work order started"),
                    ("wo_paused", "Work order paused / waiting"),
                    ("wo_closed", "Work order closed"),
                    ("wo_emergency", "Emergency work order"),
                    ("low_stock", "Low stock"),
                    ("part_shortage", "Part shortage reported"),
                    ("procurement", "Procurement"),
                    ("pm_overdue", "PM overdue"),
                    ("pm_upcoming_7d", "PM due in 7 days"),
                    ("pm_upcoming_3d", "PM due in 3 days"),
                    ("pm_upcoming_1d", "PM due tomorrow"),
                    ("pm_due_today", "PM due today"),
                    ("repair_returned", "Repair returned from vendor"),
                    ("repair_requested", "External repair requested"),
                    ("repair_draft", "External repair order created (needs vendor)"),
                    ("repair_sent", "External repair sent to vendor"),
                    ("part_received", "Part received against PO"),
                    ("vendor_return", "Vendor returned spare part"),
                    ("shortage_followup", "Shortage follow-up"),
                    ("wo_part_received", "Part received from supplier (linked to WO)"),
                    ("wo_part_returned", "Part returned from vendor (linked to WO)"),
                    ("wo_part_rejected", "Part request rejected (linked to WO)"),
                    ("wo_blocker_opened", "WO blocker opened"),
                    ("wo_blocker_resolved", "WO blocker resolved"),
                    ("wo_blocker_cancelled", "WO blocker cancelled"),
                    ("emergency_interrupted", "Emergency WO interrupted another WO"),
                    ("labor_resumed", "Labor resumed on WO"),
                    ("po_received_summary", "PO received (summary)"),
                    ("pm_morning_summary", "PM morning summary (technician)"),
                    ("pm_manager_morning", "PM manager morning summary"),
                    ("pm_new_assignment", "PM assigned to you"),
                    ("pm_returned", "PM submission returned"),
                    ("pm_overdue_tech", "PM is overdue"),
                    ("pm_overdue_manager", "PM overdue (manager alert)"),
                    ("pm_unassigned", "PM has no technician"),
                    ("pm_waiting_review", "PM awaiting manager review"),
                    ("pm_plan_paused", "PM plan paused"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="externalrepairorder",
            index=models.Index(
                fields=["supplier", "status"], name="ero_supplier_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="externalrepairorder",
            index=models.Index(
                fields=["status", "returned_at"], name="ero_status_returned_idx"
            ),
        ),
        migrations.RunPython(_backfill_ero_supplier, _backfill_ero_supplier_reverse),
    ]
