# Generated by Django 4.2.30 on 2026-07-11 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("maintenance", "0050_externalrepairorder_diagnosed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickmaintenancelog",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional single attachment (image, video, audio, or PDF).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quick_log",
                to="maintenance.attachment",
            ),
        ),
        migrations.AddField(
            model_name="quickmaintenancelog",
            name="type",
            field=models.CharField(
                choices=[
                    ("observation", "Observation"),
                    ("maintenance_note", "Maintenance"),
                    ("operation_note", "Operation"),
                ],
                db_index=True,
                default="observation",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("work_order", "Work Order"),
                    ("machine", "Machine"),
                    ("spare_part", "Spare Part"),
                    ("purchase_request", "Purchase Request"),
                    ("purchase_order", "Purchase Order"),
                    ("maintenance_issue", "Maintenance Issue"),
                    ("stock_movement", "Stock Movement"),
                    ("repair_order", "Repair Order"),
                    ("consumable_assignment", "Consumable Assignment"),
                    ("pm_schedule", "Pm Schedule"),
                    ("machine_log", "Machine Log"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="quickmaintenancelog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="quickmaintenancelog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="quickmaintenancelog",
            index=models.Index(
                fields=["machine", "-created_at"], name="qmlog_machine_recent_idx"
            ),
        ),
    ]
