# Generated by Django 4.2.30 on 2026-07-13 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0014_purchaseorder_reorder_source"),
        ("maintenance", "0051_quickmaintenancelog_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="invoice_ref",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tool",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="purchase_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="What we paid for this tool. Used for cost-of-damaged reporting.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tool",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendor who supplied this tool. Optional for legacy tools.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tools_supplied",
                to="procurement.supplier",
            ),
        ),
        migrations.CreateModel(
            name="ToolDamageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "damage_kind",
                    models.CharField(
                        choices=[
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                            ("worn_out", "Worn out / end of life"),
                            ("inherited_defect", "Defective on arrival"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "damage_reason",
                    models.TextField(
                        help_text="Why the tool was damaged or lost. Minimum 15 characters."
                    ),
                ),
                ("quantity_damaged", models.PositiveIntegerField(default=1)),
                (
                    "replacement_action",
                    models.CharField(
                        choices=[
                            ("buy_from_other", "Buy from a different supplier"),
                            ("buy_from_same", "Buy from same supplier"),
                            ("pending", "Replacement pending"),
                            ("replaced_from_stock", "Replaced from existing stock"),
                            ("no_replacement", "No replacement needed"),
                        ],
                        default="buy_from_other",
                        max_length=30,
                    ),
                ),
                (
                    "tool_status_after",
                    models.CharField(
                        default="out_of_service",
                        help_text="Tool's status after this incident. Always 'out_of_service' for now.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The assignment that ended in damage. Null for outages not tied to an open assignment.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="damage_records",
                        to="maintenance.toolassignment",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_damage_records_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot of the supplier who supplied THIS unit. Null for legacy unbranded tools.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tool_damage_records",
                        to="procurement.supplier",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        help_text="The specific unit that was damaged.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="damage_records",
                        to="maintenance.tool",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool", "-created_at"], name="tdr_tool_created_idx"
                    ),
                    models.Index(fields=["supplier"], name="tdr_supplier_idx"),
                    models.Index(fields=["damage_kind"], name="tdr_kind_idx"),
                ],
            },
        ),
    ]
