# Generated by Django 4.2.30 on 2026-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0053_phase3_emergency_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderblockerevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("blocker_created", "Blocker Created"),
                    ("blocker_resolved", "Blocker Resolved"),
                    ("blocker_cancelled", "Blocker Cancelled"),
                    ("part_request_created", "Part Request Created"),
                    ("part_approved", "Part Approved"),
                    ("part_rejected", "Part Rejected"),
                    ("part_issued", "Part Issued"),
                    ("part_received", "Part Received"),
                    ("shortage_raised", "Shortage Raised"),
                    ("shortage_decided", "Shortage Decided"),
                    ("shortage_fulfilled", "Shortage Fulfilled"),
                    ("ero_created", "Ero Created"),
                    ("ero_sent", "Ero Sent"),
                    ("ero_returned", "Ero Returned"),
                    ("ero_accepted", "Ero Accepted"),
                    ("emergency_interrupted", "Emergency Interrupted"),
                    ("labor_resumed", "Labor Resumed"),
                    ("emergency_review_approved", "Emergency Review Approved"),
                    ("emergency_review_exception", "Emergency Review Exception"),
                    ("emergency_review_investigate", "Emergency Review Investigate"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
