# Generated by Django 4.2.30 on 2026-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0055_remove_tool_supplier_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="site",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="uniq_default_site",
            ),
        ),
    ]
