# Generated by Django 4.2.30 on 2026-06-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_purchase_order_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequest",
            name="is_emergency",
        ),
        migrations.RemoveField(
            model_name="purchaserequest",
            name="urgency",
        ),
    ]
