# Generated by Django 4.2.30 on 2026-06-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0030_externalrepairorder_component_and_more"),
        ("procurement", "0006_remove_purchaserequest_is_emergency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="component",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"asset_level": 5},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="component_purchase_requests",
                to="maintenance.machine",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requests",
                to="maintenance.machine",
            ),
        ),
    ]
