# Generated by Django 4.2.30 on 2026-06-13 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0014_partissueline_related_shortage_report_and_more"),
        ("procurement", "0007_purchaserequest_component_purchaserequest_machine"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="source_shortage_report",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this PR was auto-created from a shortage decision. Null for manual PRs. SET_NULL on delete (closing the shortage does not delete the PR).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_requests",
                to="inventory.partshortagereport",
            ),
        ),
    ]
