# Generated by Django 4.2.30 on 2026-06-15 16:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0037_remove_workordercost_parts_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("procurement", "0008_purchaserequest_source_shortage_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorderitem",
            old_name="unit_price",
            new_name="negotiated_unit_price",
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="negotiated_unit_price",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Price agreed on the PO. Renamed from unit_price.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="carrier",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="condition_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="delivery_note_ref",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=1,
                help_text="PO currency → site currency at receive time",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="inspected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pos_inspected",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="invoice_attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="po_invoice_for",
                to="maintenance.attachment",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pos_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_invoice_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier_invoice_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="actual_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="What was actually invoiced by the supplier. Used for weighted-avg cost recompute.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="backordered_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Units the supplier owes but hasn't delivered. ordered_qty = received_qty + backordered_qty + cancelled_qty.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="condition",
            field=models.CharField(
                choices=[
                    ("good", "Good"),
                    ("damaged", "Damaged (quarantine)"),
                    ("rejected", "Rejected at inspection"),
                ],
                default="good",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="damaged_qty",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="line_note",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="rejected_qty",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=14
            ),
        ),
    ]
