# Generated by Django 4.2.30 on 2026-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_remove_purchaseorderitem_unit_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique supplier code. Supports Arabic, e.g. SUP-001 or مورد-001. Used in QR format SUPPLIER:{code}.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
