# Generated by Django 4.2.30 on 2026-07-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_alter_supplier_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique supplier code. Use letters, digits, and dashes (e.g. SUP-001 or MWRD-001). Used in QR format SUPPLIER:{code}.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
