# Generated by Django 4.2.30 on 2026-07-10 21:44

from django.db import migrations, models


def _backfill_supplier_type(apps, schema_editor):
    """Backfill supplier_type from the legacy is_repair_vendor boolean.

    Mapping:
        is_repair_vendor=True  → supplier_type='repair_vendor'
        is_repair_vendor=False → supplier_type='parts_supplier'

    Idempotent: only fills rows where supplier_type still equals the
    default ('parts_supplier') AND is_repair_vendor is True — i.e. we
    only promote parts_supplier → repair_vendor, never demote.
    """
    Supplier = apps.get_model("procurement", "Supplier")
    Supplier.objects.filter(
        is_repair_vendor=True,
        supplier_type="parts_supplier",
    ).update(supplier_type="repair_vendor")


def _backfill_supplier_type_reverse(apps, schema_editor):
    """No-op reverse: the supplier_type column is dropped on rollback."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_alter_supplier_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("parts_supplier", "Parts supplier"),
                    ("repair_vendor", "Repair vendor"),
                ],
                db_index=True,
                default="parts_supplier",
                help_text="What this supplier does for us: a parts supplier sells spare parts, a repair vendor fixes damaged parts. These are mutually exclusive — if a supplier does both, create two separate Supplier records.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_repair_vendor",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="DEPRECATED: derived from `supplier_type`. Kept for back-compat in queries and admin filters. Will be removed once callers are migrated.",
            ),
        ),
        migrations.RunPython(_backfill_supplier_type, _backfill_supplier_type_reverse),
    ]
