# Generated by Django 4.2.30 on 2026-07-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0013_purchaseorder_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="reorder_source",
            field=models.ForeignKey(
                blank=True,
                help_text="If this PO was created by reordering an earlier PO, the source PO's id. Lets the manager trace the lineage and view the original pricing.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reorders",
                to="procurement.purchaseorder",
            ),
        ),
    ]
