# Generated by Django 4.2.30 on 2026-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0014_purchaseorder_reorder_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
