# Generated by Django 4.2.30 on 2026-07-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0052_tool_supplier_and_damage'),
        ('inventory', '0018_stockmovement_supplier_and_more'),
        ('procurement', '0015_widen_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tool',
            field=models.ForeignKey(blank=True, help_text='Set when this PO line is for a tool (e.g. a damaged tool being reordered). Mutually exclusive with `part` — exactly one of `part` or `tool` must be set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='maintenance.tool'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.sparepart'),
        ),
    ]
