# Generated by Django 4.2.30 on 2026-07-20 13:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0016_add_tool_to_po_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="backordered_qty",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Units the supplier owes but hasn't delivered. Phase 4 invariant: ordered_qty = received_qty + backordered_qty (maintained on every receive + on close_short).",
                max_digits=14,
            ),
        ),
    ]
