# Generated by Django 4.2.30 on 2026-07-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0017_phase5_activity_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorderitem",
            name="tool",
        ),
    ]
